version: "3.8"

services:
  mailserver:
    image: tvial/docker-mailserver:release-v7.2.0
    hostname: mail
    domainname: example.com
    ports:
      - "25:25"
      - "143:143"
    volumes:
      - ./docker/mailserver/config:/tmp/docker-mailserver
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
